#!/usr/bin/perl
#
# Build project script
#
# by David M. Koltak  07/06/2018
#
# The MIT License (MIT)
# 
# Copyright (c) 2018 David M. Koltak
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# 

use Cwd 'abs_path';
use File::Basename;

if ($#ARGV != 0)
{ die "USAGE: $0 {firmware}\n"; }

my $script_dir = dirname(abs_path($0))."/";

#
# Search these paths in order, looking for rtl.lst for each package
#

my @paths = ("../../../ip/", "../../../projects/");

my @packages = ("rcn", "tawas", "de0_nano_soc");

my $project_name = "de0_nano_soc";

#
# Generate rtl file list
#

my $rtl_files = "";

push(@packages, $script_dir);

foreach my $package (@packages)
{
  my $list = '';
  my $package_dir;
  
  if ($package =~ /\/\s+$/)
  { $package_dir = $package; }
  else
  { $package_dir = $package."/"; }
  
  if ($package_dir =~ /^\//)
  {
    if (-e $package_dir."rtl.lst")
    {
      $list = $package_dir."rtl.lst";
      print " - Package '$list'\n";
    }
  }
  else
  {
    foreach $path (@paths)
    {
      my $abs_path = '';
      
      if ($path =~ /^\//)
      { $abs_path = $path; }
      else
      { $abs_path = $script_dir.$path; }
      
      if (-e $abs_path.$package_dir."rtl.lst")
      {
        $list = $abs_path.$package_dir."rtl.lst";
        print " - Package '$list'\n";
        last;
      }
    }
  }
  
  if ($list eq '')
  { die "ERROR: Unable to locate package '$package'\n"; }
  
  open(_FILE_LST_, "<$list") || die "ERROR: Unable to open '$list'\n";
  
  my $list_dir = dirname($list)."/";
  
  while (my $line = <_FILE_LST_>)
  {
    chomp $line;
    $line =~ s/^\s+//;
    if ($line eq '')
    { next; }
    if ($line =~ /^#/)
    { next; }

    my $filename = $list_dir."rtl/".$line;
    
    if (-e $filename)
    { 
      print "   + $filename\n"; 
      $rtl_files .= "set_global_assignment -name VERILOG_FILE ".$filename."\n";
    }
    else
    { die "ERROR: Unable to find '$filename'\n"; }
  }
  
  close(_FILE_LST_);
}

#
# Generate iverilog command file
#
system("rm -rf db/ incremental_db/ 2> /dev/null");
system("rm *.rpt *.smsg *.summary *.done 2> /dev/null");
system("cp $project_name.qsf.base $project_name.qsf 2> /dev/null");
open(_CMD_FILE_, ">>$project_name.qsf") || die "ERROR: Unable to open QSF file'\n";

print _CMD_FILE_ "\n";
print _CMD_FILE_ $rtl_files;

close(_CMD_FILE_);

#
# Build testcase firmware
#

my $firmware = $ARGV[0];
if (!(firmware =~ /\.mk$/))
{ $firmware .= ".mk"; }

if (!(-e $script_dir."firmware/$firmware"))
{ die "ERROR: No firmware '$firmware'\n"; }

system("rm '$script_dir"."firmware/irom.hex' 2> /dev/null");
system("rm '$script_dir"."firmware/dram.hex' 2> /dev/null");

$cmd = "cd '$script_dir"."firmware/' && make clean all -f ".$firmware;
print "RUNNING: $cmd\n";
if (system($cmd))
{ die "ERROR: Command failed\n"; }

$cmd = "cp '$script_dir"."firmware/irom.hex' ./";
print "RUNNING: $cmd\n";
if (system($cmd))
{ die "ERROR: Command failed\n"; }

$cmd = "cp '$script_dir"."firmware/dram.hex' ./";
print "RUNNING: $cmd\n";
if (system($cmd))
{ die "ERROR: Command failed\n"; }

exit 0;
