# TCL File Generated by Component Editor 18.0
# Thu Nov 01 08:12:04 CDT 2018
# DO NOT MODIFY


# 
# avalon2rcn "avalon2rcn" v1.0
#  2018.11.01.08:12:04
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module avalon2rcn
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon2rcn
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME avalon2rcn
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon2rcn
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon2rcn.v VERILOG PATH avalon2rcn.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter MASTER_ID STD_LOGIC_VECTOR 63
set_parameter_property MASTER_ID DEFAULT_VALUE 63
set_parameter_property MASTER_ID DISPLAY_NAME MASTER_ID
set_parameter_property MASTER_ID TYPE STD_LOGIC_VECTOR
set_parameter_property MASTER_ID UNITS None
set_parameter_property MASTER_ID ALLOWED_RANGES 0:127
set_parameter_property MASTER_ID HDL_PARAMETER true


# 
# display items
# 


# 
# connection point av
# 
add_interface av avalon end
set_interface_property av addressUnits WORDS
set_interface_property av associatedClock av_clk
set_interface_property av associatedReset av_rst
set_interface_property av bitsPerSymbol 8
set_interface_property av burstOnBurstBoundariesOnly false
set_interface_property av burstcountUnits WORDS
set_interface_property av explicitAddressSpan 0
set_interface_property av holdTime 0
set_interface_property av linewrapBursts false
set_interface_property av maximumPendingReadTransactions 4
set_interface_property av maximumPendingWriteTransactions 0
set_interface_property av readLatency 0
set_interface_property av readWaitTime 1
set_interface_property av setupTime 0
set_interface_property av timingUnits Cycles
set_interface_property av writeWaitTime 0
set_interface_property av ENABLED true
set_interface_property av EXPORT_OF ""
set_interface_property av PORT_NAME_MAP ""
set_interface_property av CMSIS_SVD_VARIABLES ""
set_interface_property av SVD_ADDRESS_GROUP ""

add_interface_port av av_waitrequest waitrequest Output 1
add_interface_port av av_address address Input 22
add_interface_port av av_write write Input 1
add_interface_port av av_read read Input 1
add_interface_port av av_byteenable byteenable Input 4
add_interface_port av av_writedata writedata Input 32
add_interface_port av av_readdata readdata Output 32
add_interface_port av av_readdatavalid readdatavalid Output 1
set_interface_assignment av embeddedsw.configuration.isFlash 0
set_interface_assignment av embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment av embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment av embeddedsw.configuration.isPrintableDevice 0


# 
# connection point rcn
# 
add_interface rcn conduit end
set_interface_property rcn associatedClock ""
set_interface_property rcn associatedReset ""
set_interface_property rcn ENABLED true
set_interface_property rcn EXPORT_OF ""
set_interface_property rcn PORT_NAME_MAP ""
set_interface_property rcn CMSIS_SVD_VARIABLES ""
set_interface_property rcn SVD_ADDRESS_GROUP ""

add_interface_port rcn rcn_in rcn_in Input 69
add_interface_port rcn rcn_out rcn_out Output 69


# 
# connection point av_clk
# 
add_interface av_clk clock end
set_interface_property av_clk clockRate 0
set_interface_property av_clk ENABLED true
set_interface_property av_clk EXPORT_OF ""
set_interface_property av_clk PORT_NAME_MAP ""
set_interface_property av_clk CMSIS_SVD_VARIABLES ""
set_interface_property av_clk SVD_ADDRESS_GROUP ""

add_interface_port av_clk av_clk clk Input 1


# 
# connection point av_rst
# 
add_interface av_rst reset end
set_interface_property av_rst associatedClock av_clk
set_interface_property av_rst synchronousEdges DEASSERT
set_interface_property av_rst ENABLED true
set_interface_property av_rst EXPORT_OF ""
set_interface_property av_rst PORT_NAME_MAP ""
set_interface_property av_rst CMSIS_SVD_VARIABLES ""
set_interface_property av_rst SVD_ADDRESS_GROUP ""

add_interface_port av_rst av_rst reset Input 1

